# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftDemo
pod 'SnapKit'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'Kingfisher'
pod 'RxSwift'
pod 'RxCocoa'
pod 'Moya/RxSwift'
pod 'RxDataSources', '~> 3.0'
end
